name: recipe_embed
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/csells/recipes_fat
publish_to: none

environment:
  sdk: ^3.5.2

dependencies:
  recipe_data:
    path: ../recipe_data
  google_generative_ai: ^0.4.6
  dartx: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
