name: recipes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ../../../other/flutter_ai_toolkit
  flutter_markdown: ^0.7.3+1
  gap: ^3.0.1
  go_router: ^14.2.0
  google_generative_ai: ^0.4.6
  path: ^1.9.0
  path_provider: ^2.1.4
  recipe_data:
    path: ../recipe_data
  split_view: ^3.2.1
  uuid: ^4.5.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json